### ISSUE TITLE
Sinkhorn implementation

### ISSUE THREAD

**Issue by bobye** [twistedcubic/fast_ot#1]
I was directed to this repo from a paper. I want to point out that the Sinkhorn implementation is not really ideal. It can be done a much efficient way without maintaining matrix A. This trick was documented in the original paper of Sinkhorn. 

I have a simple matlab version adopting this trick. By maintaining two vectors u, v, one can perform Sinkhorn OT in a much efficient way. 
https://github.com/bobye/OT_demo/blob/master/OptimalTransport_IBP_Sinkhorn.m

**Comment by twistedcubic** [comment]
Hi Jianbo, thanks for looking at our repo.

We are aware of this technique -- maintaining just the two vectors of ratios. We agree that if we were to form A in each step, it would be redundant. 

However we are scaling A in-place at each step, furthermore the initial allocation of A is not included in the timing. In this low-level implementation we can also ensure that the memory allocated is contiguous, making in-place operation is very efficient. Note that when scaling A in-place, the number of operations is the same as when retaining just the two vectors.

Indeed we benchmarked these variants of the implementation, including when replacing [this loop](https://github.com/twistedcubic/fast_ot/blob/master/MatrixRescaling/Sinkhorn.cpp#L105) with another BLAS operation, this version is the fastest.

**Comment by bobye** [comment]
Hi Yihe,

Please take a quick look of my pull request. With this code change, you can run the same Sinkhorn with about 1/20 time of your original implementation.

Jianbo

**Comment by twistedcubic** [comment]
Hi Jianbo,

Thanks for the PR, I looked through the code and it looks good. 

I'm testing it right now. As well as checking how much of the time improvement came from running the content of [this loop](https://github.com/twistedcubic/fast_ot/blob/master/MatrixRescaling/Sinkhorn.cpp#L119) once every 100 iter. I'm checking to see if we benchmarked a version of the code where part of that loop is run once every k iterations (ie the `if (1)` held a different conditional). 

Yihe

**Comment by bobye** [comment]
I tried the set `if (1)` in your original code to a different condition, I do see a bit improvement. Usually checking convergence condition is done at much lower frequency of iterations (as a common practice), so they would not be factored into significant portion of the overall time.  

The new implementation (as suggested in Marco Cuturi's paper) took a quite different approach and has very different speed nature as your original implementation, each iteration is done even faster than checking convergence condition.

**Comment by twistedcubic** [comment]
Right when benchmarking we did check convergence less frequently, otherwise the `if (1)` would be gratuitous. The current version is likely a debug version. 

I tested and PR and will merge it, with a credit to you. I'm benchmarking the Sinkhorn runs again, I will find out the exact implementation that was used for the timings reported so the difference can be put in the right perspective.

**Comment by bobye** [comment]
Cool!
